//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnglishCenter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Course()
        {
            this.Grades = new HashSet<Grade>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string courseLevel { get; set; }
        public string module { get; set; }
        public string duration { get; set; }
        public Nullable<System.DateTime> beginDay { get; set; }
        public Nullable<System.DateTime> endDay { get; set; }
        public string time { get; set; }
        public string room { get; set; }
        public int teacherId { get; set; }
        public int studentId { get; set; }
    
        public virtual Course_Schedule Course_Schedule { get; set; }
        public virtual Student Student { get; set; }
        public virtual Teacher Teacher { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Grade> Grades { get; set; }
        public virtual Homework Homework { get; set; }
        public virtual Picture Picture { get; set; }
    }
}
