//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnglishCenter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course_Schedule
    {
        public Nullable<int> lesson { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string unit_and_grade { get; set; }
        public string lessonAims { get; set; }
        public string notes { get; set; }
        public string teacher { get; set; }
        public string TA { get; set; }
        public int courseId { get; set; }
    
        public virtual Course Course { get; set; }
    }
}
