//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnglishCenter.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EnglishCenterDBEntities : DbContext
    {
        public EnglishCenterDBEntities()
            : base("name=EnglishCenterDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Attendance> Attendances { get; set; }
        public virtual DbSet<Course> Courses { get; set; }
        public virtual DbSet<Course_Schedule> Course_Schedule { get; set; }
        public virtual DbSet<Grade> Grades { get; set; }
        public virtual DbSet<Homework> Homework { get; set; }
        public virtual DbSet<Manager> Managers { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TA> TAs { get; set; }
        public virtual DbSet<Teacher> Teachers { get; set; }
    }
}
