//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnglishCenter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grade
    {
        public Nullable<double> attendance { get; set; }
        public Nullable<double> courseProject { get; set; }
        public Nullable<double> homework { get; set; }
        public Nullable<double> MMT { get; set; }
        public Nullable<double> EOCT { get; set; }
        public Nullable<double> total { get; set; }
        public int courseId { get; set; }
        public int teacherId { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
