//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnglishCenter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Homework
    {
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<double> score { get; set; }
        public Nullable<double> total { get; set; }
        public int courseId { get; set; }
    
        public virtual Course Course { get; set; }
    }
}
